#!/usr/bin/env python3
from argparse import ArgumentParser
from pathlib import Path
from xml.sax.saxutils import escape


def build_opml(title_id: str, feed_title: str, category: str) -> str:
    feed_url = (
        "http://manga-feeds.freshrss.svc.cluster.local:8080/"
        f"gangan-online/{title_id}.xml"
    )
    html_url = f"https://www.ganganonline.com/title/{title_id}"
    return "\n".join(
        [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<opml version="2.0">',
            "  <head>",
            "    <title>manga-feeds import</title>",
            "  </head>",
            "  <body>",
            f'    <outline text="{escape(category)}">',
            (
                f'      <outline text="{escape(feed_title)}" type="rss" '
                f'xmlUrl="{escape(feed_url)}" htmlUrl="{escape(html_url)}" '
                'description="Gangan ONLINE chapter feed generated by manga-feeds" />'
            ),
            "    </outline>",
            "  </body>",
            "</opml>",
            "",
        ]
    )


def main() -> None:
    parser = ArgumentParser(description="Generate FreshRSS OPML for manga-feeds.")
    parser.add_argument("--title-id", required=True, help="Gangan ONLINE title ID")
    parser.add_argument("--feed-title", required=True, help="FreshRSS feed title")
    parser.add_argument("--category", default="Comic", help="FreshRSS category")
    parser.add_argument("--output", help="Output path; stdout when omitted")
    args = parser.parse_args()

    opml = build_opml(args.title_id, args.feed_title, args.category)
    if args.output:
        Path(args.output).write_text(opml, encoding="utf-8")
    else:
        print(opml, end="")


if __name__ == "__main__":
    main()
